# -*- coding: utf-8 -*-
"""Student_Performance_Decision_Tree_Minimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1u_zq5OLn11nvHTjBerNlUIRqj6_FIi
"""

import pandas as pd

df=pd.read_csv("D:/Project18/Student_Performance_DT - Student_Performance_DT.csv")

df.head()

df.info()

df.describe()

df.isna().sum()

X=df.drop("Final_Result",axis=1)
y=df["Final_Result"]

X=pd.get_dummies(X,columns=["Internet_Access","Extracurricular"],drop_first=True)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred,average='weighted')
recall=recall_score(y_test,y_pred,average='weighted')
f1=f1_score(y_test,y_pred,average='weighted')

accuracy,precision,recall,f1

from sklearn.model_selection import GridSearchCV

param_grid={'criterion':['gini','entropy','log_loss'],'max_depth':[None,3,5,7,10,15],'min_samples_split':[2,5,10],'min_samples_leaf':[1,2,4]}

grid=GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1
)

grid.fit(X_train,y_train)

grid.best_params_

tuned_model=grid.best_estimator_
y_pred_tuned=tuned_model.predict(X_test)

tuned_accuracy=accuracy_score(y_test,y_pred_tuned)
tuned_precision=precision_score(y_test,y_pred_tuned,average='weighted')
tuned_recall=recall_score(y_test,y_pred_tuned,average='weighted')
tuned_f1=f1_score(y_test,y_pred_tuned,average='weighted')

tuned_accuracy,tuned_precision,tuned_recall,tuned_f1

comparison=pd.DataFrame({
    'Metric':['Accuracy','Precision','Recall','F1-score'],
    'Default':[accuracy,precision,recall,f1],
    'Tuned':[tuned_accuracy,tuned_precision,tuned_recall,tuned_f1]
})

comparison['Improvement']=comparison['Tuned']-comparison['Default']

comparison

print("\nDefault Model")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

print("\nBest Parameters")
print(grid.best_params_)

print("\nTuned Model")
print("Accuracy:", tuned_accuracy)
print("Precision:", tuned_precision)
print("Recall:", tuned_recall)
print("F1-score:", tuned_f1)

print("\nModel Comparison")
print(comparison)

if tuned_f1 > f1:
    print("\nHyperparameter tuning improved the model performance.")
elif tuned_f1 < f1:
    print("\nHyperparameter tuning did not improve the model performance.")
else:
    print("\nHyperparameter tuning produced the same model performance.")